export const ROUTE = {
  TAB: {
    CONTENT: 'ContentTab',
    COMMUNITY: 'Community',
    LINK: 'Link',
    MESSAGE: 'Message',
    MY: 'My',
  },
  MY: {
    ACCOUNT: 'Account',
    INQUIRY_LIST: 'Inquiry',
    INQUIRY_DETAIL: 'InquiryDetail',
    INQUIRY_FORM: 'InquiryForm',
    RECEIVED_POSITION_SUGGESTION_LIST: 'ReceivedSuggestion',
    RECEIVED_POSITION_SUGGESTION_DETAIL: 'ReceivedSuggestionDetail',
    APPLICANT_STATUS: 'ApplicantStatus',
    APPLICATION_STATUS: 'ApplicationStatus',
    BLACKLIST: 'Blacklist',
    CENTER_RECRUITMENT: 'CenterRecruitment',
    CERTITY_INSTRUCTOR_FORM: 'CertifyInstructorForm',
    CERTIFY_INSTRUCTOR: 'CertifyInstructor',
    CERTIFY_LOCATION: 'CertifyLocation',
    COMPANY_INFO: 'CompanyInfo',
    FOLLOWING_MANAGE: 'FollowingManage',
    LINK_ADD: 'LinkAdd',
    NOTIFICATION: 'MyNotification',
    PROFILE: 'MyProfile',
    PROFILE_EDIT: 'ProfileEdit',
    NOTICE_LIST: 'NoticeList',
    NOTICE_DETAIL: 'NoticeDetail',
    NOTIFICATION_SETTING: 'NotificationSetting',
    RESUME_CREATE: 'ResumeCreate',
    RESUME_EDIT: 'ResumeEdit',
    RESUME_MANAGE: 'ResumeManage',
    REVIEW_CREATE: 'ReviewCreate',
    REVIEW_EDIT: 'ReviewEdit',
    REVIEW_MANAGE: 'ReviewManage',
    SEND_SUGGESTION_DETAIL: 'SendSuggestionDetail',
    SEND_SUGGESTION: 'SendSuggestion',
    SETTING: 'Setting',
    VERSION: 'Version',
  },
  COMMUNITY: {
    POST_CREATE: 'CommunityPostCreate',
    COMMENT_EDIT: 'CommunityCommentEdit',
    POST_EDIT: 'CommunityPostEdit',
    POST_DETAIL: 'CommunityPost',
    MY: 'CommunityMy',
  },
  AUTH: {
    FIND_EMAIL: 'FindEmail',
    PASSWORD_CHANGE: 'PasswordChange',
    PASSWORD_RESET: 'PasswordReset',
    SIGN_IN_EMAIL: 'SignInEmail',
    SIGN_IN_PASSWORD: 'SignInPassword',
    SIGN_UP: 'SignUp',
    COMPANY_SIGN_UP_FORM: 'CompanySignUpForm',
    SIGN_UP_FORM: 'SignUpForm',
    TERMS_AGREEMENT: 'TermsAgreement',
  },
  RECRUIT: {
    LIST: 'RecruitList',
    CREATE: 'RecruitCreate',
    EDIT: 'RecruitEdit',
    MAP: 'RecruitMap',
  },
  RESUME: {
    PREVIEW: 'ResumePreview',
  },
  INSTRUCTOR: {
    LIST: 'InstructorList',
    PROFILE: 'Profile',
  },
  CENTER: {
    INFO: 'CenterInfo',
    PROFILE_EDIT: 'CenterProfileEdit',
  },
  TERM: {
    LIST: 'TermList',
    DETAIL: 'TermDetail',
  },
  PROFILE: 'Profile',
  GALLERY: 'Gallery',
  SUGGESTION: 'Suggestion',
} as const;
