export const iconPath = {
  LOGO: require('@images/logo.png'),
  FAVORITE: require('@images/icon/favorite.png'),
  MESSAGE: require('@images/icon/message.png'),
  BOOKMARK: require('@images/icon/bookmark.png'),
  MORE_VERT: require('@images/icon/more_vert.png'),
  TAB_BAR_ICON_1: require('@images/icon/tabBarIcon_1.png'),
  TAB_BAR_ICON_1_ON: require('@images/icon/tabBarIcon_1_on.png'),
  TAB_BAR_ICON_2: require('@images/icon/tabBarIcon_2.png'),
  TAB_BAR_ICON_2_ON: require('@images/icon/tabBarIcon_2_on.png'),
  TAB_BAR_ICON_3: require('@images/icon/tabBarIcon_3.png'),
  TAB_BAR_ICON_3_ON: require('@images/icon/tabBarIcon_3_on.png'),
  TAB_BAR_ICON_4: require('@images/icon/tabBarIcon_4.png'),
  TAB_BAR_ICON_4_ON: require('@images/icon/tabBarIcon_4_on.png'),
  BELL: require('@images/icon/bell.png'),
  BELL_ON: require('@images/icon/bell_on.png'),
  MY: require('@images/icon/my.png'),
};
